# Generated by Django 4.2.18 on 2025-10-10 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='age',
            field=models.IntegerField(default=30, verbose_name='Возраст'),
        ),
        migrations.AddField(
            model_name='profile',
            name='aim_weight',
            field=models.IntegerField(default=70, verbose_name='Цель веса'),
        ),
        migrations.AddField(
            model_name='profile',
            name='calories',
            field=models.DecimalField(decimal_places=1, default=1766, max_digits=10, verbose_name='Калорийность'),
        ),
        migrations.AddField(
            model_name='profile',
            name='carbohydrates',
            field=models.DecimalField(decimal_places=1, default=161, max_digits=10, verbose_name='Углеводы'),
        ),
        migrations.AddField(
            model_name='profile',
            name='fats',
            field=models.DecimalField(decimal_places=1, default=70, max_digits=10, verbose_name='Жиры'),
        ),
        migrations.AddField(
            model_name='profile',
            name='height',
            field=models.IntegerField(default=170, verbose_name='Рост'),
        ),
        migrations.AddField(
            model_name='profile',
            name='proteins',
            field=models.DecimalField(decimal_places=1, default=123, max_digits=10, verbose_name='Белки'),
        ),
        migrations.AddField(
            model_name='profile',
            name='weight',
            field=models.IntegerField(default=70, verbose_name='Вес'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='default_profile.webp', upload_to='profile_images/'),
        ),
    ]
