# Generated by Django 4.2.18 on 2025-10-10 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_age_profile_aim_weight_profile_calories_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='sex',
            field=models.TextField(default='мужчина'),
        ),
    ]
