# Generated by Django 4.2.18 on 2025-10-13 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='aim_weight',
            field=models.DecimalField(decimal_places=1, default=80, max_digits=10, verbose_name='Цель'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='calories',
            field=models.DecimalField(decimal_places=0, default=1766, max_digits=10, verbose_name='Калорийность'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='carbohydrates',
            field=models.DecimalField(decimal_places=0, default=161, max_digits=10, verbose_name='Углеводы'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='fats',
            field=models.DecimalField(decimal_places=0, default=70, max_digits=10, verbose_name='Жиры'),
        ),
    ]
