# Generated by Django 4.2.18 on 2025-10-13 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_profile_aim_weight_alter_profile_calories_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='aim_weight',
            field=models.DecimalField(decimal_places=0, default=80, max_digits=10, verbose_name='Цель'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='proteins',
            field=models.DecimalField(decimal_places=0, default=123, max_digits=10, verbose_name='Белки'),
        ),
    ]
