# Generated by Django 4.2.18 on 2025-10-14 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_profile_aim_weight_alter_profile_proteins'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='max_streak',
            field=models.IntegerField(default=1, verbose_name='максимальный стрик'),
        ),
    ]
