# Generated by Django 4.2.18 on 2025-10-15 08:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0025_alter_product_thumbnail_alter_product_title'),
        ('accounts', '0006_profile_max_streak'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='standard',
            field=models.JSONField(default=dict, verbose_name='Целевые показатели'),
        ),
        migrations.CreateModel(
            name='DayStandard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.day')),
                ('standard', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='day_standard', to='accounts.profile')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='day_standard', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
