# Generated by Django 4.2.18 on 2025-10-15 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_profile_standard_daystandard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daystandard',
            name='standard',
            field=models.ForeignKey(blank=True, default=dict, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='day_standard', to='accounts.profile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='aim_weight',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Цель'),
        ),
    ]
