# Generated by Django 4.2.18 on 2025-10-15 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_daystandard_standard_alter_profile_aim_weight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='standard',
        ),
        migrations.DeleteModel(
            name='DayStandard',
        ),
    ]
