# Generated by Django 4.2.18 on 2025-10-15 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_profile_standard_delete_daystandard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='aim_weight',
            field=models.IntegerField(default=0, verbose_name='Цель'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='calories',
            field=models.IntegerField(default=1766, verbose_name='Калорийность'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='carbohydrates',
            field=models.IntegerField(default=161, verbose_name='Углеводы'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='fats',
            field=models.IntegerField(default=70, verbose_name='Жиры'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='proteins',
            field=models.IntegerField(default=123, verbose_name='Белки'),
        ),
    ]
