# Generated by Django 4.2.18 on 2025-10-15 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_profile_aim_weight_alter_profile_calories_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
        migrations.AlterField(
            model_name='profile',
            name='calories',
            field=models.IntegerField(default=0, verbose_name='Калорийность'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='carbohydrates',
            field=models.IntegerField(default=0, verbose_name='Углеводы'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='fats',
            field=models.IntegerField(default=0, verbose_name='Жиры'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='height',
            field=models.IntegerField(default=175, verbose_name='Рост'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='proteins',
            field=models.IntegerField(default=0, verbose_name='Белки'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='weight',
            field=models.IntegerField(default=75, verbose_name='Вес'),
        ),
    ]
