# Generated by Django 4.2.18 on 2025-10-16 05:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_remove_profile_bio_alter_profile_calories_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='birthday',
            field=models.DateField(default=datetime.date(1991, 12, 21), verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='age',
            field=models.IntegerField(default=0, verbose_name='Возраст'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='max_streak',
            field=models.IntegerField(default=0, verbose_name='максимальный стрик'),
        ),
    ]
