# Generated by Django 4.2.18 on 2025-10-16 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_profile_birthday_alter_profile_age_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='sex',
        ),
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('male', 'мужчина'), ('female', 'женщина')], default='мужчина', verbose_name='Пол'),
        ),
    ]
