# Generated by Django 4.2.18 on 2025-10-16 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_remove_profile_sex_profile_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(default='', verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='profile',
            name='surname',
            field=models.CharField(default='', verbose_name='Фамилия'),
        ),
    ]
