# Generated by Django 4.2.18 on 2025-10-17 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_profile_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='age',
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('мужской', 'мужской'), ('женский', 'женский')], default='мужчина', verbose_name='Пол'),
        ),
    ]
