# Generated by Django 4.2.18 on 2025-02-10 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='thumbnail',
            field=models.ImageField(blank=True, default='default.png', upload_to='images/thumbnails/%Y/%m/%d/', verbose_name='Изображение продукта'),
        ),
        migrations.AlterModelTable(
            name='product',
            table='Products',
        ),
    ]
