# Generated by Django 4.2.18 on 2025-02-12 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_product_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='thumbnail',
            field=models.ImageField(blank=True, default='default.png', upload_to='images/thumbnails/', verbose_name='Изображение продукта'),
        ),
    ]
