# Generated by Django 4.2.18 on 2025-02-13 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_product_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, verbose_name='URL'),
        ),
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=255, verbose_name='URL')),
                ('create', models.DateTimeField(auto_now=True, verbose_name='Время создания')),
                ('update', models.DateTimeField(auto_now=True, verbose_name='Время обновления')),
                ('date', models.DateField(auto_now_add=True, unique=True, verbose_name='Дата')),
                ('proteins', models.FloatField(default=0)),
                ('fats', models.FloatField(default=0)),
                ('carbohydrates', models.FloatField(default=0)),
                ('weight', models.IntegerField(default=0)),
                ('calories', models.FloatField()),
                ('products', models.ManyToManyField(related_name='day', to='catalog.product')),
            ],
        ),
    ]
