# Generated by Django 4.2.18 on 2025-02-13 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_product_slug_day'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='day',
            options={'ordering': ['date'], 'verbose_name': 'День', 'verbose_name_plural': 'Дни'},
        ),
        migrations.AlterModelTable(
            name='day',
            table='Day',
        ),
    ]
