# Generated by Django 4.2.18 on 2025-02-17 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_alter_day_options_alter_day_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='calories',
            field=models.FloatField(default=0),
        ),
    ]
