# Generated by Django 4.2.18 on 2025-03-03 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_alter_day_calories_alter_day_carbohydrates_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='day',
            name='products',
        ),
        migrations.CreateModel(
            name='DayProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(decimal_places=1, max_digits=10)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.day')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.product')),
            ],
            options={
                'unique_together': {('day', 'product')},
            },
        ),
    ]
