# Generated by Django 4.2.18 on 2025-03-05 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_remove_day_products_dayproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='weight',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='dayproduct',
            name='weight',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.IntegerField(),
        ),
    ]
