# Generated by Django 4.2.18 on 2025-03-21 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_alter_day_weight_alter_dayproduct_weight_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='day',
            name='weight',
        ),
        migrations.AddField(
            model_name='day',
            name='user_weight',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='day',
            name='calories',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='day',
            name='carbohydrates',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='day',
            name='create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='day',
            name='fats',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='day',
            name='proteins',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=10),
        ),
    ]
