# Generated by Django 4.2.18 on 2025-04-04 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_remove_day_weight_day_user_weight_alter_day_calories_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='date',
            field=models.DateField(unique=True, verbose_name='Дата'),
        ),
    ]
