# Generated by Django 4.2.18 on 2025-04-09 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_alter_day_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='dayproduct',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dayproduct',
            name='weight',
            field=models.IntegerField(default=0),
        ),
    ]
