# Generated by Django 4.2.18 on 2025-04-10 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_dayproduct_quantity_alter_dayproduct_weight'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dayproduct',
            options={'verbose_name': 'Продукты дня', 'verbose_name_plural': 'Продукты дня'},
        ),
        migrations.AlterUniqueTogether(
            name='dayproduct',
            unique_together=set(),
        ),
        migrations.AlterModelTable(
            name='dayproduct',
            table='Day_Product',
        ),
    ]
