# Generated by Django 4.2.18 on 2025-04-10 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_alter_dayproduct_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='dayproduct',
            table='DayProduct',
        ),
    ]
