# Generated by Django 4.2.18 on 2025-04-10 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_alter_dayproduct_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dayproduct',
            old_name='quantity',
            new_name='calories',
        ),
    ]
