# Generated by Django 4.2.18 on 2025-04-24 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_rename_quantity_dayproduct_calories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='calories',
            field=models.DecimalField(decimal_places=1, max_digits=10, verbose_name='Калорийность'),
        ),
        migrations.AlterField(
            model_name='product',
            name='carbohydrates',
            field=models.DecimalField(decimal_places=1, max_digits=10, verbose_name='Углеводы'),
        ),
        migrations.AlterField(
            model_name='product',
            name='fats',
            field=models.DecimalField(decimal_places=1, max_digits=10, verbose_name='Жиры'),
        ),
        migrations.AlterField(
            model_name='product',
            name='proteins',
            field=models.DecimalField(decimal_places=1, max_digits=10, verbose_name='Белки'),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.IntegerField(verbose_name='Вес порции'),
        ),
    ]
