# Generated by Django 4.2.18 on 2025-04-24 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0018_alter_product_calories_alter_product_carbohydrates_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='thumbnail',
            field=models.ImageField(default='default.png', upload_to='images/thumbnails/', verbose_name='Изображение продукта'),
        ),
    ]
