# Generated by Django 4.2.18 on 2025-05-21 15:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0019_alter_product_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='dayproduct',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='day_products', to=settings.AUTH_USER_MODEL),
        ),
    ]
