# Generated by Django 4.2.18 on 2025-05-24 17:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0020_dayproduct_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dayproduct',
            old_name='user',
            new_name='user_id',
        ),
        migrations.AddField(
            model_name='day',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='day', to=settings.AUTH_USER_MODEL),
        ),
    ]
