# Generated by Django 4.2.18 on 2025-05-24 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0021_rename_user_dayproduct_user_id_day_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='day',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='dayproduct',
            old_name='user_id',
            new_name='user',
        ),
    ]
