# Generated by Django 4.2.18 on 2025-08-28 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0022_rename_user_id_day_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='date',
            field=models.DateField(verbose_name='Дата'),
        ),
    ]
