# Generated by Django 4.2.18 on 2025-08-28 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0023_alter_day_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, verbose_name='URL'),
        ),
    ]
