# Generated by Django 4.2.18 on 2025-10-15 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0025_alter_product_thumbnail_alter_product_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='standard',
            field=models.JSONField(default=dict, verbose_name='Целевые показатели'),
        ),
    ]
